FROM public.ecr.aws/amazonlinux/amazonlinux:2

# so we can install the console tools
RUN yum install -y java-1.8.0 wget tar

RUN wget \
    https://archive.apache.org/dist/kafka/3.9.1/kafka_2.13-3.9.1.tgz \
    && tar xzf kafka_2.13-3.9.1.tgz \
    && rm kafka_2.13-3.9.1.tgz

RUN wget https://github.com/aws/aws-msk-iam-auth/releases/download/v2.3.2/aws-msk-iam-auth-2.3.2-all.jar \
    -P kafka_2.13-3.9.1/libs/

# keep the container alive so we can exec in
ENTRYPOINT [ "sleep", "3600" ]